#spring.application.name=bookstore
#spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
#spring.datasource.username=postgres
#spring.datasource.password=postgresalasana
#spring.jpa.show-sql=true
#spring.data.rest.base-path=/rest
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=none









