#spring.application.name=bookstore

#H2-tietokannan osoite
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb

#Näytä tietokantaan kohdistuvat toimenpiteet terminaalissa
#spring.jpa.show-sql=true
